function addLoadEvent(a){var b=window.onload;window.onload="function"!=typeof window.onload?a:function(){b();a()}}function insertAfter(a,b){var c=b.parentNode;c.lastChild==b?c.appendChild(a):c.insertBefore(a,b.nextSibling)}function addClass(a,b){a.className=a.className?a.className+" "+b:b}
function highlightPages(){if(!document.getElementsByTagName)return!1;var a=document.getElementsByTagName("header");if(1>a.length)return!1;a=a[0].getElementsByTagName("nav");if(1>a.length)return!1;for(var a=a[0].getElementsByTagName("a"),b=0;b<a.length;b++){var c=a[b].getAttribute("href");-1!=window.location.href.indexOf(c)&&(a[b].className="here",c=a[b].lastChild.nodeValue.toLowerCase(),document.body.setAttribute("id",c))}}addLoadEvent(highlightPages);
function moveElement(a,b,c,e){if(!document.getElementById||!document.getElementById(a))return!1;var d=document.getElementById(a);d.movement&&clearTimeout(d.movement);d.style.left||(d.style.left="0px");d.style.top||(d.style.top="0px");var f=parseInt(d.style.left),g=parseInt(d.style.top),h;if(f==b&&g==c)return!0;f<b&&(h=Math.ceil((b-f)/10),f+=h);f>b&&(h=Math.ceil((f-b)/10),f-=h);g<c&&(h=Math.ceil((c-g)/10),g+=h);g>c&&(h=Math.ceil((g-c)/10),g-=h);d.style.left=f+"px";d.style.top=g+"px";d.movement=setTimeout("moveElement('"+
a+"',"+b+","+c+","+e+")",e)}
function prepareSlideShow(){if(!document.getElementById||!document.getElementsByTagName||!document.getElementById("intro"))return!1;var a=document.getElementById("intro"),b=document.createElement("div");b.setAttribute("id","slideShow");var c=document.createElement("img");c.setAttribute("id","frame");c.setAttribute("src","images/frame.gif");c.setAttribute("alt","");b.appendChild(c);c=document.createElement("img");c.setAttribute("id","preview");c.setAttribute("src","images/slideshow.gif");c.setAttribute("alt",
"a glimpse of what awaits you");b.appendChild(c);insertAfter(b,a);for(var a=document.getElementsByTagName("a"),e,b=0;b<a.length;b++)a[b].onmouseover=function(){e=this.getAttribute("href");-1!=e.indexOf("index.html")&&moveElement("preview",0,0,5);-1!=e.indexOf("about.html")&&moveElement("preview",-150,0,5);-1!=e.indexOf("photos.html")&&moveElement("preview",-300,0,5);-1!=e.indexOf("live.html")&&moveElement("preview",-450,0,5);-1!=e.indexOf("contact.html")&&moveElement("preview",-600,0,5)}}addLoadEvent(prepareSlideShow);
function showSection(a){if(!document.getElementsByTagName)return!1;var b=document.getElementsByTagName("section");if(1>b.length)return!1;for(var c=0;c<b.length;c++)b[c].getAttribute("id")!=a?b[c].style.display="none":b[c].style.display="block"}
function prepareInternalnav(){if(!document.getElementsByTagName||!document.getElementById)return!1;var a=document.getElementsByTagName("article");if(1>a.length)return!1;a=a[0].getElementsByTagName("nav");if(1>a.length)return!1;for(var a=a[0].getElementsByTagName("a"),b=0;b<a.length;b++){var c=a[b].getAttribute("href").split("#")[1];document.getElementById(c)&&(document.getElementById(c).style.display="none",a[b].destination=c,a[b].onclick=function(){showSection(this.destination);return!1})}}addLoadEvent(prepareInternalnav);
function showPic(a){if(!document.getElementById("placeholder"))return!0;var b=document.getElementById("placeholder"),c=a.getAttribute("href");b.setAttribute("src",c);if(!document.getElementById("description"))return!1;b=document.getElementById("description");a=a.getAttribute("title")?a.getAttribute("title"):"";3==b.lastChild.nodeType&&(b.lastChild.nodeValue=a);return!1}
function preparePlaceholder(){if(!document.getElementById||!document.createElement)return!1;var a=document.createElement("img");a.setAttribute("id","placeholder");a.setAttribute("src","images/placeholder.gif");a.setAttribute("alt","my image gallery");var b=document.createElement("p");b.setAttribute("id","description");var c=document.createTextNode("Choose an image");b.appendChild(c);if(!document.getElementById("imagegallery"))return!1;c=document.getElementById("imagegallery");insertAfter(b,c);insertAfter(a,
b)}function prepareGallery(){if(!document.getElementsByTagName||!document.getElementById||!document.getElementById("imagegallery"))return!1;for(var a=document.getElementById("imagegallery").getElementsByTagName("a"),b=0;b<a.length;b++)a[b].onclick=function(){return showPic(this)}}addLoadEvent(preparePlaceholder);addLoadEvent(prepareGallery);
function stripeTables(){if(!document.getElementsByTagName)return!1;var a=document.getElementsByTagName("table");if(1>a.length)return!1;for(var a=a[0].getElementsByTagName("tr"),b=!1,c=0;c<a.length;c++)b?(b=!1,addClass(a[c],"odd")):b=!0}
function highlightRows(){if(!document.getElementsByTagName||1>document.getElementsByTagName("table").length)return!1;for(var a=document.getElementsByTagName("tr"),b=0;b<a.length;b++)a[b].oldClassName=a[b].className,a[b].onmouseover=function(){addClass(this,"highlight")},a[b].onmouseout=function(){this.className=this.oldClassName}}
function displayAbbreviation(){if(!document.getElementsByTagName||!document.createElement||!document.createTextNode)return!1;var a=document.getElementsByTagName("abbr");if(1>a.length)return!1;for(var b=[],c=0;c<a.length;c++){var e=a[c];if(!(1>e.childNodes.length)){var d=e.getAttribute("title"),e=e.lastChild.nodeValue;b[d]=e}}a=document.createElement("dl");for(d in b){e=b[d];c=document.createElement("dt");e=document.createTextNode(e);c.appendChild(e);var e=document.createElement("dd"),f=document.createTextNode(d);
e.appendChild(f);a.appendChild(c);a.appendChild(e)}b=document.createElement("h3");d=document.createTextNode("Abbreviations");b.appendChild(d);d=document.getElementsByTagName("article");if(1>d.length)return!1;d=d[0];d.appendChild(b);d.appendChild(a)}addLoadEvent(stripeTables);addLoadEvent(highlightRows);addLoadEvent(displayAbbreviation);
function focusLabels(){if(!document.getElementsByClassName)return!1;for(var a=document.getElementsByClassName("label"),b=0;b<a.length;b++){var c=a[b].getAttribute("for");document.getElementById(c)&&document.getElementById(c).focus()}}addLoadEvent(focusLabels);
function resetFields(a){if(!(Modernizr.input.placeholder||1>a.elements.length))for(var b=0;b<a.elements.length;b++){var c=a.elements[b];if(c.placeholder||c.getAttribute("placeholder"))c.onfocus=function(){var a=this.placeholder||this.getAttribute("placeholder");this.value==a&&(this.value=this.className="")},c.onblur=function(){""==this.value&&(this.value=this.placeholder||this.getAttribute("placeholder"),this.className="placeholder")},c.onblur()}}
function isFilled(a){if(0==a.value.replace(" ","").length)return!1;var b=a.placeholder||a.getAttribute("placehoder");return a.value!=b}function isEmail(a){return-1!=a.value.indexOf("@")&&-1!=a.value.indexOf(".")}
function validateForm(a){for(var b=0;b<a.elements.length;b++){var c=a.elements[b];if("required"==c.required&&!isFilled(c))return alert("Please fill in the "+c.name+" field."),!1;if("email"==c.type&&!isEmail(c))return alert("The "+c.name+" field must be a valid email address."),!1}return!0}
function prepareForms(){for(var a=0;a<document.forms.length;a++){var b=document.forms[a];resetFields(b);b.onsubmit=function(){if(!validateForm(this))return!1;var a=document.getElementsByTagName("article")[0];return submitFormWithAjax(this,a)?!1:!0}}}
function getHTTPObject(){"undefined"==typeof XMLHttpRequest&&(XMLHttpRequest=function(){try{return new ActiveXObject("Msxml2.XMLHTTP.6.0")}catch(a){}try{return new ActiveXObject("Msxml2.XMLHTTP.3.9")}catch(a){}try{return new ActiveXObject("Msxml2.XMLHTTP")}catch(a){}});return new XMLHttpRequest}
function displayAjaxLoading(a){for(;a.hasChildNodes();)a.removeChild(a.lastChild);var b=document.createElement("img");b.setAttribute("src","images/loading.gif");b.setAttribute("alt","Loading...");a.appendChild(b)}
function submitFormWithAjax(a,b){var c=getHTTPObject();if(!c)return!1;displayAjaxLoading(b);for(var e=[],d,f=0;f<a.elements.length;f++)d=a.elements[f],e[f]=d.name+"="+encodeURIComponent(d.value);e=e.join("&");c.open("POST",a.getAttribute("action"),!0);c.setRequestHeader("Content-type","application/x-www-form-urlencoded");c.onreadystatechange=function(){if(4==c.readyState)if(200==c.status||0==c.status){var a=c.responseText.match(/<article>([\s\S]+)<\/article>/);0<a.length?b.innerHTML=a[1]:b="<p>Oops. there was an error, Sorry.</p>"}else b=
"<p>"+c.statusText+"</p>"};c.send(e);return!0}addLoadEvent(prepareForms);
